# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Example' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # 公有库
  pod 'AFNetworking', '~> 3.0'
  pod 'SDWebImage'
  pod 'YYKit'
  
  target 'ExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
